### PR TITLE
Use latest mongo v2.2

### PR DESCRIPTION
**Pull request by jgeurts**

### CODE REVIEW

**Comment by mikermcneil** [comment]
@jgeurts thanks!

**Comment by mikermcneil** [comment]
@jgeurts Would you pin the SVR?  (i.e. remove the tilde)  Other than that, ready to merge and publish!

**Comment by jgeurts** [comment]
@mikermcneil Should be all set. Thanks!

**Comment by mikermcneil** [comment]
@jgeurts thanks!

**Pull request merged**
